name: 🐛 Content Bug Report
description: Report typos, broken links, or errors in published work
title: "[BUG] <short description>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Found something broken in the magazine? Let us know here!
  - type: input
    id: location
    attributes:
      label: Where is the issue?
      placeholder: "e.g., Page 12 of Issue 03, 'The Summer Poem'"
  - type: textarea
    id: description
    attributes:
      label: What's the bug?
  - type: textarea
    id: suggestion
    attributes:
      label: Suggest a fix (optional)
      validations:
        required: false
  - type: input
    id: contributor
    attributes:
      label: Your Name
      placeholder: "e.g., Kritika Singh"
  - type: input
    id: email
    attributes:
      label: Your Email
      placeholder: "e.g., kritika@example.com"
  - type: input
    id: org
    attributes:
      label: Are you participating via an organization? (Optional)
      placeholder: "e.g., GSSoC, SoC, DWG"
      validations:
        required: false
